// Auto-generated by Maze
package tests;

import nl.uu.maze.example.ExampleClass;
import org.junit.jupiter.api.Test;

public class ExampleClassTest {
  @Test
  public void testPrint1() {
    int arg0 = 0;
    ExampleClass.print(arg0);
  }

  @Test
  public void testPrint2() {
    int arg0 = -2147483648;
    ExampleClass.print(arg0);
  }

  @Test
  public void testPrint3() {
    int arg0 = 1;
    ExampleClass.print(arg0);
  }
}
