// Auto-generated by Maze
package tests;

import nl.uu.maze.example.ExampleClass;
import org.junit.jupiter.api.Test;

public class ExampleClassTest {
  @Test
  public void testPrint1() {
    int p0 = 0;
    ExampleClass.print(p0);
  }

  @Test
  public void testPrint2() {
    int p0 = 1;
    ExampleClass.print(p0);
  }
}
