// Auto-generated by Maze
package tests;

import nl.uu.maze.example.SimpleExample;
import org.junit.jupiter.api.Test;

public class SimpleExampleTest {
  @Test
  public void testFoobar1() {
    int arg0 = 10;
    int arg1 = 0;
    SimpleExample cut = new SimpleExample();
    cut.foobar(arg0, arg1);
  }

  @Test
  public void testFoobar2() {
    int arg0 = 11;
    int arg1 = 5;
    SimpleExample cut = new SimpleExample();
    cut.foobar(arg0, arg1);
  }

  @Test
  public void testFoobar3() {
    int arg0 = 11;
    int arg1 = 4;
    SimpleExample cut = new SimpleExample();
    cut.foobar(arg0, arg1);
  }
}
