// Auto-generated by Maze
package tests;

import nl.uu.maze.example.TriangleClassifier;
import org.junit.jupiter.api.Test;

public class TriangleClassifierTest {
  @Test
  public void testClassifyTriangle1() {
    int arg0 = 0;
    int arg1 = 0;
    int arg2 = 0;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle2() {
    int arg0 = 1;
    int arg1 = 0;
    int arg2 = 0;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle3() {
    int arg0 = 2147483647;
    int arg1 = 2147467263;
    int arg2 = 2147483646;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle4() {
    int arg0 = 544735160;
    int arg1 = 992000147;
    int arg2 = 9439264;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle5() {
    int arg0 = 268435664;
    int arg1 = 134235757;
    int arg2 = 134235757;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle6() {
    int arg0 = 8192;
    int arg1 = 8030;
    int arg2 = 261;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle7() {
    int arg0 = 409361741;
    int arg1 = 46959104;
    int arg2 = 409361741;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle8() {
    int arg0 = 734975;
    int arg1 = 734975;
    int arg2 = 1058049;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle9() {
    int arg0 = 65537;
    int arg1 = 65537;
    int arg2 = 65537;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle10() {
    int arg0 = 536870910;
    int arg1 = 16;
    int arg2 = 19;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }

  @Test
  public void testClassifyTriangle11() {
    int arg0 = 1;
    int arg1 = 1;
    int arg2 = 0;
    TriangleClassifier cut = new TriangleClassifier();
    cut.classifyTriangle(arg0, arg1, arg2);
  }
}
